<div class="container-fluid">
    <table class="table table-hover animated fadeInUp">
        <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Title</th>
                <th scope="col">First Name</th>
                <th scope="col">Last Name</th>
                <th scope="col">Photo</th>
                <th scope="col"></th>
                <th scope = 'col'></th >
            </tr>
        </thead>
        <tbody>
            <?php
                viewContacts();
            ?>
        </tbody>
    </table>
</div>

